### ISSUE TITLE
Implementation Error

### ISSUE THREAD

**Issue by theodoruszq** [nrupatunga/PY-GOTURN#14]
In `example_generator.py` module, there is a serious mistake which could make the whole program fail.

https://github.com/nrupatunga/PY-GOTURN/blob/79b6d6eae3c57b0a7a46883586182497e51faad2/goturn/helper/BoundingBox.py#L193

AND

https://github.com/nrupatunga/PY-GOTURN/blob/79b6d6eae3c57b0a7a46883586182497e51faad2/goturn/helper/BoundingBox.py#L213

The two lines uses wrong  brackets of logic gates. Please check it.

**Comment by nrupatunga** [comment]
Im checking this issue. I will let you know the update.

**Comment by nrupatunga** [comment]
This issue is fixed. Thank you @sydney0zq  for pointing out the error. 
Updated as below:

https://github.com/nrupatunga/PY-GOTURN/blob/da303ad92603cb6457f56819579171dc6d22c2e9/goturn/helper/BoundingBox.py#L203

https://github.com/nrupatunga/PY-GOTURN/blob/da303ad92603cb6457f56819579171dc6d22c2e9/goturn/helper/BoundingBox.py#L223
